"""add rgritten

Revision ID: 068df46915c1
Revises: 6aec7357b5fe
Create Date: 2025-11-26 19:45:58.975582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068df46915c1'
down_revision = '6aec7357b5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rgritten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('rittype', sa.String(length=255), nullable=False),
    sa.Column('ritnummer', sa.Integer(), nullable=False),
    sa.Column('schema', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('weekdag', sa.String(length=255), nullable=True),
    sa.Column('aankomst', sa.String(length=255), nullable=True),
    sa.Column('vertrek', sa.String(length=255), nullable=True),
    sa.Column('voornaam', sa.String(length=255), nullable=True),
    sa.Column('voorletters', sa.String(length=255), nullable=True),
    sa.Column('voorvoegsels', sa.String(length=255), nullable=True),
    sa.Column('achternaam', sa.String(length=255), nullable=True),
    sa.Column('straat', sa.String(length=255), nullable=True),
    sa.Column('huisnummer', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=255), nullable=True),
    sa.Column('woonplaats', sa.String(length=255), nullable=True),
    sa.Column('telefoonnummer', sa.String(length=255), nullable=True),
    sa.Column('faxnummer', sa.String(length=255), nullable=True),
    sa.Column('mobiel', sa.String(length=255), nullable=True),
    sa.Column('emailadres', sa.String(length=255), nullable=True),
    sa.Column('geslacht', sa.String(length=255), nullable=True),
    sa.Column('geboortedatum', sa.DateTime(), nullable=True),
    sa.Column('co_bijzonderheden', sa.String(length=255), nullable=True),
    sa.Column('huisnummer_toev', sa.String(length=255), nullable=True),
    sa.Column('land', sa.String(length=255), nullable=True),
    sa.Column('afdeling', sa.String(length=255), nullable=True),
    sa.Column('kamernummer', sa.String(length=255), nullable=True),
    sa.Column('cor_straat', sa.String(length=255), nullable=True),
    sa.Column('cor_huisnummer', sa.String(length=255), nullable=True),
    sa.Column('cor_huisnummer_toev', sa.String(length=255), nullable=True),
    sa.Column('cor_postcode', sa.String(length=255), nullable=True),
    sa.Column('cor_woonplaats', sa.String(length=255), nullable=True),
    sa.Column('cor_land', sa.String(length=255), nullable=True),
    sa.Column('cor_afdeling', sa.String(length=255), nullable=True),
    sa.Column('cor_kamernummer', sa.String(length=255), nullable=True),
    sa.Column('co_klantnummer', sa.String(length=255), nullable=True),
    sa.Column('emailadres2', sa.String(length=255), nullable=True),
    sa.Column('emailadres3', sa.String(length=255), nullable=True),
    sa.Column('klantnummer2', sa.String(length=255), nullable=True),
    sa.Column('tp_id', sa.Integer(), nullable=True),
    sa.Column('tp_byzonderheden', sa.String(length=255), nullable=True),
    sa.Column('pasnummer', sa.String(length=255), nullable=True),
    sa.Column('ind_rolstoel', sa.Integer(), nullable=True),
    sa.Column('rolstoel_type', sa.Integer(), nullable=True),
    sa.Column('ind_begeleiding_sociaal', sa.Integer(), nullable=True),
    sa.Column('ind_begeleiding_medisch', sa.Integer(), nullable=True),
    sa.Column('ind_beperking_lichamelijk', sa.Integer(), nullable=True),
    sa.Column('ind_beperking_verstandelijk', sa.Integer(), nullable=True),
    sa.Column('ind_hulphond', sa.Integer(), nullable=True),
    sa.Column('ind_voorin_in_taxi', sa.Integer(), nullable=True),
    sa.Column('ind_kamer_tot_kamer_vervoer', sa.Integer(), nullable=True),
    sa.Column('ind_gezinstaxi', sa.Integer(), nullable=True),
    sa.Column('ind_personenauto', sa.Integer(), nullable=True),
    sa.Column('ind_lage_instap', sa.Integer(), nullable=True),
    sa.Column('ind_voldoende_beenruimte', sa.Integer(), nullable=True),
    sa.Column('ind_rollator', sa.Integer(), nullable=True),
    sa.Column('ind_beperking_visueel', sa.Integer(), nullable=True),
    sa.Column('ind_beperking_auditief', sa.Integer(), nullable=True),
    sa.Column('ind_autisme', sa.Integer(), nullable=True),
    sa.Column('ind_individueel_vervoer', sa.Integer(), nullable=True),
    sa.Column('beschikkingnummer', sa.String(length=255), nullable=True),
    sa.Column('vervoer_type', sa.Integer(), nullable=True),
    sa.Column('vervoer_type_omschrijving', sa.String(length=255), nullable=True),
    sa.Column('rolstoel_type_omschrijving', sa.String(length=255), nullable=True),
    sa.Column('aantal_gezinstaxi', sa.Integer(), nullable=True),
    sa.Column('aantal_begeleiding_sociaal', sa.Integer(), nullable=True),
    sa.Column('aantal_begeleiding_medisch', sa.Integer(), nullable=True),
    sa.Column('ind_scootmobiel', sa.Integer(), nullable=True),
    sa.Column('ind_strippen', sa.Integer(), nullable=True),
    sa.Column('aantal_strippen', sa.Integer(), nullable=True),
    sa.Column('ind_voldoende_zithoogte', sa.Integer(), nullable=True),
    sa.Column('ind_afwijkend_tarief', sa.Integer(), nullable=True),
    sa.Column('ind_zithulp', sa.Integer(), nullable=True),
    sa.Column('zithulp_type', sa.Integer(), nullable=True),
    sa.Column('financiering_type', sa.Integer(), nullable=True),
    sa.Column('ind_belservice', sa.Integer(), nullable=True),
    sa.Column('ind_epilepsie', sa.Integer(), nullable=True),
    sa.Column('ind_geen_warme_overdracht', sa.Integer(), nullable=True),
    sa.Column('extra_instap_heen', sa.Integer(), nullable=True),
    sa.Column('extra_instap_terug', sa.Integer(), nullable=True),
    sa.Column('extra_uitstap_heen', sa.Integer(), nullable=True),
    sa.Column('extra_uitstap_terug', sa.Integer(), nullable=True),
    sa.Column('ind_kleinschalig', sa.Integer(), nullable=True),
    sa.Column('max_reistijd', sa.Integer(), nullable=True),
    sa.Column('ind_extra1', sa.Integer(), nullable=True),
    sa.Column('ind_extra2', sa.Integer(), nullable=True),
    sa.Column('ind_extra3', sa.Integer(), nullable=True),
    sa.Column('ind_extra4', sa.Integer(), nullable=True),
    sa.Column('ind_extra5', sa.Integer(), nullable=True),
    sa.Column('ind_busbegeleider_nodig', sa.Integer(), nullable=True),
    sa.Column('ind_is_busbegeleider', sa.Integer(), nullable=True),
    sa.Column('ind_inclusief_begeleider', sa.Integer(), nullable=True),
    sa.Column('ind_alleen_begeleider', sa.Integer(), nullable=True),
    sa.Column('ind_invloed_op_factuur', sa.Integer(), nullable=True),
    sa.Column('ind_client_mag_rit_wijzigen', sa.Integer(), nullable=True),
    sa.Column('ind_ontheffing_mondkapje', sa.Integer(), nullable=True),
    sa.Column('ind_ontheffing_gordelplicht', sa.Integer(), nullable=True),
    sa.Column('ind_bus', sa.Integer(), nullable=True),
    sa.Column('ind_mag_vraagafhankelijk', sa.Integer(), nullable=True),
    sa.Column('budget_standaard', sa.String(length=255), nullable=True),
    sa.Column('budget_huidig', sa.String(length=255), nullable=True),
    sa.Column('ind_alleen_zitten', sa.Integer(), nullable=True),
    sa.Column('ind_diabetes', sa.Integer(), nullable=True),
    sa.Column('ind_deur_deur', sa.Integer(), nullable=True),
    sa.Column('ind_anderstalig', sa.Integer(), nullable=True),
    sa.Column('ind_opvouwbare_rolstoel', sa.Integer(), nullable=True),
    sa.Column('ind_kinderstoel', sa.Integer(), nullable=True),
    sa.Column('ind_stoelverhoger', sa.Integer(), nullable=True),
    sa.Column('ind_gordelkapje', sa.Integer(), nullable=True),
    sa.Column('ind_meerpuntsgordel', sa.Integer(), nullable=True),
    sa.Column('ind_maxicosi', sa.Integer(), nullable=True),
    sa.Column('ind_begeleiding_niet_verplicht', sa.Integer(), nullable=True),
    sa.Column('ind_afasie', sa.Integer(), nullable=True),
    sa.Column('ind_vaste_zitplaats', sa.Integer(), nullable=True),
    sa.Column('ind_gordelverlenging', sa.Integer(), nullable=True),
    sa.Column('ind_lifo', sa.Integer(), nullable=True),
    sa.Column('ind_filo', sa.Integer(), nullable=True),
    sa.Column('ind_fifo', sa.Integer(), nullable=True),
    sa.Column('aantal_kleinschalig', sa.Integer(), nullable=True),
    sa.Column('minimaal_scootmobiel_reisafstand', sa.Integer(), nullable=True),
    sa.Column('minimale_reisafstand', sa.Integer(), nullable=True),
    sa.Column('ind_vervroegde_belservice', sa.Integer(), nullable=True),
    sa.Column('ind_opstappunt_verplicht', sa.Integer(), nullable=True),
    sa.Column('ind_bagage', sa.Integer(), nullable=True),
    sa.Column('type_bagage', sa.String(length=255), nullable=True),
    sa.Column('ind_niet_combineren', sa.Integer(), nullable=True),
    sa.Column('niet_combineren_met', sa.String(length=255), nullable=True),
    sa.Column('locatie_van', sa.String(length=255), nullable=True),
    sa.Column('straat_van', sa.String(length=255), nullable=True),
    sa.Column('huisnummer_van', sa.String(length=255), nullable=True),
    sa.Column('huisnummer_toev_van', sa.String(length=255), nullable=True),
    sa.Column('postcode_van', sa.String(length=255), nullable=True),
    sa.Column('plaats_van', sa.String(length=255), nullable=True),
    sa.Column('locatie_naar', sa.String(length=255), nullable=True),
    sa.Column('straat_naar', sa.String(length=255), nullable=True),
    sa.Column('huisnummer_naar', sa.String(length=255), nullable=True),
    sa.Column('huisnummer_toev_naar', sa.String(length=255), nullable=True),
    sa.Column('postcode_naar', sa.String(length=255), nullable=True),
    sa.Column('plaats_naar', sa.String(length=255), nullable=True),
    sa.Column('weekdag_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('vervoerder', sa.String(length=255), nullable=False),
    sa.Column('opdrachtgever', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('ritdatum', sa.DateTime(), nullable=True),
    sa.Column('routenummer', sa.String(length=255), nullable=True),
    sa.Column('vervoerder_routenummer', sa.String(length=255), nullable=True),
    sa.Column('instap', sa.Time(), nullable=True),
    sa.Column('uitstap', sa.Time(), nullable=True),
    sa.Column('afstand', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('duur', sa.Time(), nullable=True),
    sa.Column('afstand2', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('duur2', sa.Time(), nullable=True),
    sa.Column('zoneafstand1', sa.Integer(), nullable=True),
    sa.Column('zoneafstand2', sa.Integer(), nullable=True),
    sa.Column('perceel_id', sa.Integer(), nullable=True),
    sa.Column('perceel_omschrijving', sa.String(length=255), nullable=True),
    sa.Column('gemeld_op', sa.DateTime(), nullable=True),
    sa.Column('afwezig_van', sa.DateTime(), nullable=True),
    sa.Column('afwezig_totmet', sa.DateTime(), nullable=True),
    sa.Column('attendance_reason', sa.String(length=255), nullable=True),
    sa.Column('tekst', sa.String(length=255), nullable=True),
    sa.Column('instelling_gemeld_op', sa.DateTime(), nullable=True),
    sa.Column('instelling_afwezig_van', sa.DateTime(), nullable=True),
    sa.Column('instelling_afwezig_totmet', sa.DateTime(), nullable=True),
    sa.Column('instelling_reden', sa.String(length=255), nullable=True),
    sa.Column('instelling_tekst', sa.String(length=255), nullable=True),
    sa.Column('vervangt_plannedtransport_id', sa.Integer(), nullable=True),
    sa.Column('vervangt_datum', sa.DateTime(), nullable=True),
    sa.Column('realisatie_route', sa.String(length=255), nullable=True),
    sa.Column('instapgerealiseerd', sa.Time(), nullable=True),
    sa.Column('instaplatitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('instaplongitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('uitstapgerealiseerd', sa.Time(), nullable=True),
    sa.Column('uitstaplatitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('uitstaplongitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('loosmeldinggerealiseerd', sa.Time(), nullable=True),
    sa.Column('loosmeldinglatitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('loosmeldinglongitude', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'ritnummer', name='uq_rgritten_owner_ritnummer')
    )
    with op.batch_alter_table('rgritten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rgritten_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rgritten_ritnummer'), ['ritnummer'], unique=False)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rgritten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rgritten_ritnummer'))
        batch_op.drop_index(batch_op.f('ix_rgritten_owner_id'))

    op.drop_table('rgritten')
    # ### end Alembic commands ###
